[package]
authors = [
    "KPN",
    "Frank Hol <frank.hol@kpn.com>",
]
description = "SDK for KPN Data Services Hub"
edition = "2021"
exclude = ["/tmp"]
homepage = "https://www.kpn.com/zakelijk/internet-of-things/data-services-hub.htm"
keywords = ["kpn", "dsh", "sdk"]
license = "Apache License 2.0"
name = "dsh_sdk"
readme = "README.md"
repository = "https://github.com/kpn-dsh/dsh-sdk-platform-rs"
version = "0.1.0"

[dependencies]
tokio = { version = "1", features = ["signal", "sync", "time", "macros"], optional = true}
tokio-util = {version = "0.7", optional = true}
rdkafka =  { version = "0.36", features =  ["cmake-build"], optional = true}
rustls = "0.21"
serde = { version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
picky = { version =  "7.0.0-rc.8", default-features = false, features = ["x509"]}
reqwest = { version = "0.11" , default-features = false, features = ["rustls-tls", "tokio-rustls"] }
log =  "0.4"
thiserror = "1.0"
prometheus = { version = "0.13", features = ["process"], optional = true }
warp = { version = "0.3", optional = true}
lazy_static  = { version = "1.4", optional = true}

[features]
default = ["graceful_shutdown", "local", "metrics", "rdkafka-ssl"]
full = ["graceful_shutdown", "local", "metrics", "rdkafka-ssl", "dlq"]
local = []
metrics =  ["prometheus", "warp", "lazy_static"]
dlq = ["tokio"]
graceful_shutdown = ["tokio", "tokio-util"]
rdkafka-ssl-vendored = ["rdkafka" ,"rdkafka/ssl-vendored"]
rdkafka-ssl = ["rdkafka", "rdkafka/ssl"]


[dev-dependencies]
mockito = "1.1.1"
tokio = "1"
