[package]
name = "dsh-rs-example"
version = "0.1.0"
description = "An example of DSH service using the dsh-sdk crate" 
edition = "2021"

[dependencies]
# path needs to be changed to the path of the dsh_sdks crate
dsh_sdk = { version = "0.1", features = ["rdkafka-ssl-vendored"] }
log = "0.4"
env_logger = "0.11"
tokio = { version = "^1.35", features = ["full"] }